# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxIUMwc12PhXJRkxui_hjtvbVvZAz5Ca
"""

from flask import Flask, request, jsonify
import joblib
import numpy as np

# Initialize Flask app
app = Flask(__name__)

# Load the trained model (make sure mental_health_model.pkl is in repo root)
model = joblib.load("mental_health_model.pkl")

@app.route("/")
def home():
    return "✅ Student Mental Health API is running!"

@app.route("/predict", methods=["POST"])
def predict():
    try:
        # Expecting input JSON like: {"features": [val1, val2, val3, ...]}
        data = request.json
        features = np.array(data["features"]).reshape(1, -1)

        # Predict
        prediction = model.predict(features)

        return jsonify({"prediction": str(prediction[0])})
    except Exception as e:
        return jsonify({"error": str(e)}), 400


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)